modelArtifacts:
  uri: "pvc://granite-41-8b-fp8-pvc/hub/ibm-granite/granite-4.1-8b-fp8"
  name: "ibm-granite/granite-4.1-8b-fp8"
  size: 20Gi
  authSecretName: "llm-d-hf-token"
  labels:
    app: "vllm-granite-41-8b-fp8"

routing:
  servicePort: 8000

accelerator:
  type: nvidia

decode:
  containers:
    - name: "vllm"
      image: "vllm/vllm-openai:v0.19.0"
      modelCommand: vllmServe
      args:
        - "--enable-auto-tool-choice"
        - "--tool-call-parser"
        - "granite4"
        - "--disable-access-log-for-endpoints"
        - "/health,/metrics,/ping"
        - "--trust-remote-code"
      env:
        - name: HOME
          value: /tmp
      mountModelVolume: true

prefill:
  create: false
