apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: bbr
  namespace: agentgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  traffic:
    phase: PreRouting
    transformation:
      request:
        set:
        - name: X-Gateway-Base-Model-Name
          value: |
            {
              "google/gemma-4-26B-A4B-it": "google/gemma-4-26B-A4B-it",
              "RedHatAI/gemma-4-26B-A4B-it-FP8-Dynamic": "RedHatAI/gemma-4-26B-A4B-it-FP8-Dynamic",
              "RedHatAI/gemma-4-31B-it-FP8-block": "RedHatAI/gemma-4-31B-it-FP8-block",
              "ibm-granite/granite-4.0-h-small": "ibm-granite/granite-4.0-h-small",
              "ibm-granite/granite-4.1-30b-fp8": "ibm-granite/granite-4.1-30b-fp8",
              "ibm-granite/granite-4.1-8b-fp8": "ibm-granite/granite-4.1-8b-fp8",
              "Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled": "Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled",
              "Qwen/Qwen3.5-35B-A3B": "Qwen/Qwen3.5-35B-A3B",
              "Qwen/Qwen3.5-9B": "Qwen/Qwen3.5-9B",
              "Qwen/Qwen3-Next-80B-A3B-Thinking": "Qwen/Qwen3-Next-80B-A3B-Thinking"
            }[json(request.body).model]
