modelArtifacts:
  uri: "pvc://gemma-4-26b-a4b-pvc/hub/RedHatAI/gemma-4-26B-A4B-it-FP8-Dynamic"
  name: "RedHatAI/gemma-4-26B-A4B-it-FP8-Dynamic"
  size: 40Gi
  authSecretName: "llm-d-hf-token"
  labels:
    app: "vllm-gemma-4-26b-a4b" # Must match inferencePool.modelServers.matchLabels.app

routing:
  servicePort: 8000

accelerator:
  type: nvidia

decode:
  containers:
    - name: "vllm"
      image: "vllm/vllm-openai:gemma4"
      modelCommand: vllmServe
      args:
        - "--enable-auto-tool-choice"
        - "--tool-call-parser"
        - "gemma4"
        - "--disable-access-log-for-endpoints"
        - "/health,/metrics,/ping"
        - "--trust-remote-code"
      env:
        - name: HOME
          value: /tmp
      volumeMounts:
        - name: gemma4-patch
          mountPath: /usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/gemma4.py
          subPath: gemma4.py
      mountModelVolume: true
  volumes:
    - name: gemma4-patch
      configMap:
        name: gemma4-patched

prefill:
  create: false
